### PR TITLE
CI: Add Ruby 3.2, 3.1

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR adds two more CI matrix elements, for the in-support Ruby versions.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Gotta bump to latest of Ubuntu perhaps

**Comment by olleolleolle** [comment]
@artemave There.

**Comment by artemave** [comment]
Still failing, but I think if you rebase then it'll pass.

**Comment by olleolleolle** [comment]
Rebased, @artemave.

**Comment by artemave** [comment]
Nice one - thanks!

**Comment by olleolleolle** [comment]
I like this repo, a nice little thing.

**Pull request merged**
